# Generated by Django 5.2.11 on 2026-02-13 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='商品名')),
                ('category', models.CharField(choices=[('STATIONERY', '文房具'), ('OFFICE', 'オフィス用品'), ('OTHER', 'その他')], default='OTHER', max_length=20, verbose_name='カテゴリ')),
                ('price', models.PositiveIntegerField(verbose_name='単価')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventory.product', verbose_name='商品')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='在庫数')),
                ('threshold', models.PositiveIntegerField(default=10, verbose_name='アラート閾値')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '在庫',
                'verbose_name_plural': '在庫',
                'db_table': 'inventories',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='発注数量')),
                ('status', models.CharField(choices=[('PENDING', '発注中'), ('ORDERED', '発注済み'), ('RECEIVED', '入荷済み'), ('CANCELLED', 'キャンセル')], default='PENDING', max_length=20, verbose_name='ステータス')),
                ('ordered_at', models.DateTimeField(blank=True, null=True, verbose_name='発注日時')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='入荷日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '発注',
                'verbose_name_plural': '発注',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IN', '入庫'), ('OUT', '出庫')], max_length=10, verbose_name='種別')),
                ('quantity', models.PositiveIntegerField(verbose_name='数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='実行日時')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '取引履歴',
                'verbose_name_plural': '取引履歴',
                'db_table': 'transactions',
            },
        ),
    ]
